version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: eslint-plugin-ember
    versions:
    - 10.1.2
    - 10.2.0
    - 10.3.0
    - 10.4.1
  - dependency-name: eslint
    versions:
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: ember-cli-babel
    versions:
    - 7.25.0
    - 7.26.1
    - 7.26.2
    - 7.26.3
  # Ignore "ember-maybe-in-element" until we drop lts-3.16 support (bumping to 2.1.0 fails the build on that version)
  - dependency-name: ember-maybe-in-element
  commit-message:
    prefix: "[chore]"
