version: 2
updates:
- package-ecosystem: npm
  directory: "/addon"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  allow:
  - dependency-name: "@ember/test-waiters"
  - dependency-name: "@embroider/addon-shim"
  - dependency-name: "@floating-ui/dom"
  - dependency-name: "ember-maybe-in-element"
  ignore:
  - dependency-name: "*"
    update-types: ["version-update:semver-major"]
  commit-message:
    prefix: "[chore]"
